### ISSUE TITLE
Using and managing shared computational infrastructure: Tracking and exposing usage information

### ISSUE THREAD

**Issue by lheagy** [pangeo-data/jupyter-earth#17]
To enable more efficient usage and administration of JupyterHubs on shared computational infrastructure, we will build tools to: 
- [ ] collect actionable metrics about resource usage including CPU and Memory usage, available Disk space, or hardware and software failures within JupyterHub deployments
- [ ] expose these metrics to users so they can adapt their computational work accordingly
- [ ] expose these metrics to administrators so they can plan & customize the deployment to better meet user’s needs

The outcome of this work will be a customizable template that can be included in JupyterHub deployments that follow the Zero to JupyterHub guide.

**Comment by lheagy** [comment]
#7 would make progress on this
