### ISSUE TITLE
JMTE workshop at the EarthCube meeting 

### ISSUE THREAD

**Issue by whyjz** [pangeo-data/jupyter-earth#51]
As per our conversation from the last two meetings, here are some plans and to-dos for the upcoming Jupyter Meets the Earth workshop. My memory might be wrong so please correct me if you see anything strange here!

# Plans 

- [Google doc link for tentative agenda and timeline](https://docs.google.com/document/d/1L5EGMlfznQXOMpZnZy5gGPWfpdCrhIkAlC4PMhcsPKk/edit#)
- Workshop length is 1.5 hours
- Use live, online presentation as well as 3 breakout Zoom rooms to address a large size of the audience
- Update the Github pages for more self-guided resources and future references. 

# To-dos

- [x] Finalize the main topic(s) for the entire workshop 
- [x] Finalize the number of sessions and their topic
- Create content
  - [x] Opening remark: The Jupyter landscape. & Illustrate with real research and education use cases. (@fperez and Edom)
  - [x] Using Jupyter in a research project: toy workflow presentation (@whyjz and #59)
  - [x] Breakout sessions A: Exploratory analysis: JLab, Widgets, IPython, RetroLab (@fperez )
  - [x] Breakout sessions B: Cloud native workflows at scale: JHub, Dask, Intake, RTC (@consideRatio, [notes](https://docs.google.com/document/d/1JHnM_POMmX5CzraKxOJ0XGdiwCJ8exgoyHZRU9XrZOI/edit), [slides](https://docs.google.com/presentation/d/1ZB-gtW6Lcyg2hqUPODNvg9QNL_f3_0XTwJmLzcibEDA/edit))
  - [x] Breakout sessions C: Sharing, publishing, repro: nbviewer, JBook, Binder, GitHub (@whyjz )
- [x] Make Google Form survey (@fperez; also @lrennels will help conduct the survey at the workshop)
- [x] Make https://hydro.jupytearth.org and https://workflow.jupytearth.org point to @whyjz and @EMscience's GitHub pages (@consideRatio)
  - [x] @whyjz visit the settings, set a custom domain workflow.jupytearth.org, and then after a while when you can press the Force HTTPS checkbox.
  - [x] @EMscience visit the settings, set a custom domain workflow.jupytearth.org, and then after a while when you can press the Force HTTPS checkbox.

Please feel free to add anything you come up with at any time!

**Comment by whyjz** [comment]
As we successfully hosted the JMTE workshop at the EarthCube meeting, I am closing this issue now but will follow up on the remaining tasks (e.g. #61) in a separate thread or two.
